name: Create new release draft

on:
  # Trigger on all pull request events
  pull_request:

  # Trigger when main has changes
  push:
    branches:
      - main

jobs:
  push:
    name: Draft a new release

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      # https://github.com/release-drafter/release-drafter
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        with:
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}