name: Create new release draft

on:
  # Trigger on all pull request events
  pull_request:

  # Trigger when main has changes
  push:
    branches:
      - main

jobs:
  push:
    name: Draft a new release

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      # https://github.com/release-drafter/release-drafter
      - uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        with:
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}